export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const PRODUCT_LOADING_ERROR = "PRODUCT_LOADING_ERROR";
export const SET_CURRENCY = "SET_CURRENCY";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
